### ISSUE TITLE
creatng the TB_data.csv?

### ISSUE THREAD

**Issue by rkiddy** [tc10287/TB_data_analysis_California#1]
Where did the data that you have here come from?

I am looking at making an workable version of the data at https://data.chhs.ca.gov/dataset/healthcare-facility-locations. You did not use any of that, yes? Your TB cases do not seem to be broken down by geo.

**Comment by tc10287** [comment]
I got the data from here
https://data.chhs.ca.gov/dataset/tuberculosis-cases-and-rates/resource/926f95db-ae9c-490e-a534-26a4dd9d3596

**Comment by rkiddy** [comment]
Thanx!
